;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        back-to-indentation-or-beginning-of-line
        duplicate-current-line-or-region
        end-of-visual-line
        indent-for-tab-command
        kill-region
        kill-to-beginning-of-line
        kill-visual-line
        org-delete-char
        orgtbl-self-insert-command
        sp--self-insert-command
        sp-backward-delete-char
        sp-delete-char
        sp-splice-sexp
        zap-up-to-char
        ))
