;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        back-to-indentation-or-beginning-of-line
        beginning-of-buffer
        comment-or-uncomment-current-line-or-region
        dired-back-to-start-of-files
        dired-toggle-marks
        dired-toggle-read-only
        drag-stuff-up
        duplicate-current-line-or-region
        emmet-expand-line
        end-of-buffer
        end-of-visual-line
        eval-print-last-sexp
        hippie-expand-no-case-fold
        indent-for-tab-command
        kill-region
        kill-to-beginning-of-line
        kill-visual-line
        kmacro-end-or-call-macro
        markdown-cycle
        markdown-exdent-or-delete
        my-increment-number-at-point
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-force-self-insert
        org-kill-line
        org-return-indent
        org-self-insert-command
        org-todo
        org-yank
        orgtbl-self-insert-command
        python-indent-shift-left
        python-indent-shift-right
        slime-space
        smex
        sp--self-insert-command
        sp-backward-delete-char
        sp-backward-sexp
        sp-delete-char
        sp-forward-sexp
        sp-forward-slurp-sexp
        sp-splice-sexp
        text-scale-adjust
        wdired-exit
        yaml-electric-backspace
        yaml-electric-dash-and-dot
        zap-up-to-char
        ))

(setq mc/cmds-to-run-once
      '(
        coffee-dedent-line-backspace
        counsel-M-x
        describe-key
        drag-stuff-down
        help-for-help
        js2-mode-show-node
        org-cycle
        shell-command-on-region
        zzz-up-to-char
        ))
