(source melpa)
(source marmalade)
(source org)
(source gnu)

(depends-on "cask")
(depends-on "palette")

(depends-on "ack-and-a-half")
(depends-on "ag")
(depends-on "auto-complete")
(depends-on "coffee-mode")
(depends-on "eldoc") ;; ???
(depends-on "ert") ;; ???
(depends-on "flx-ido")
(depends-on "flycheck")
(depends-on "haml-mode")
(depends-on "ido-vertical-mode")
(depends-on "ido-at-point")
(depends-on "ido-ubiquitous")
(depends-on "macrostep") ;; ???
(depends-on "magit") ;; Git in Emacs.
(depends-on "markdown-mode")
(depends-on "molokai-theme")
(depends-on "monokai-theme")
(depends-on "multiple-cursors")
(depends-on "powerline")
(depends-on "popup")
(depends-on "projectile")
(depends-on "quickrun")
(depends-on "rainbow-delimiters")
(depends-on "saveplace")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "solarized-theme")
(depends-on "use-package")
(depends-on "visual-regexp")
(depends-on "visual-regexp-steroids")
(depends-on "yasnippet")
(depends-on "yaml-mode")
(depends-on "zenburn-theme")
