(source melpa)
(source marmalade)
(source org)
(source gnu)

(depends-on "cask")
(depends-on "palette")

(depends-on "ack-and-a-half")
(depends-on "ag")
(depends-on "auto-complete")
(depends-on "coffee-mode")
(depends-on "cyberpunk-theme")
(depends-on "eldoc") ;; enable elisp docs on the modeline
(depends-on "elpy")
(depends-on "expand-region")
(depends-on "flx")
(depends-on "flx-ido")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "haml-mode")
(depends-on "grizzl")
(depends-on "ido-at-point")
(depends-on "ido-ubiquitous")
(depends-on "ido-vertical-mode")
(depends-on "macrostep") ;; expansion of macros in Emacs Lisp source code
(depends-on "magit") ;; git in Emacs.
(depends-on "markdown-mode")
(depends-on "molokai-theme")
(depends-on "monokai-theme")
(depends-on "multiple-cursors")
(depends-on "popup")
(depends-on "powerline")
(depends-on "projectile")
(depends-on "projectile-rails")
(depends-on "quickrun")
(depends-on "rainbow-delimiters")
(depends-on "robe")
(depends-on "ruby-test-mode")
(depends-on "ruby-tools")
(depends-on "saveplace")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "solarized-theme")
(depends-on "use-package")
(depends-on "visual-regexp")
(depends-on "visual-regexp-steroids")
(depends-on "yaml-mode")
(depends-on "yasnippet")
(depends-on "zenburn-theme")
